CREATE SCHEMA IF NOT EXISTS sdc;

CREATE TABLE IF NOT EXISTS sdc.template_sdc (
    template_sdc_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sdc_form_design_sdcid text NULL,
    base_uri text NULL,
    lineage text NULL,
    version text NULL,
    full_uri text NULL,
    form_title text NULL,
    sdc_xml text NULL,
    doc_type text NULL
);

CREATE TABLE IF NOT EXISTS sdc.template_item (
    template_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_sdc_id integer NOT NULL REFERENCES sdc.template_sdc(template_sdc_id),
    parent_template_item_id integer NULL REFERENCES sdc.template_item(template_item_id),
    template_item_sdcid text NOT NULL,
    type text NULL,
    visible_text text NULL,
    invisible_text text NULL,
    min_card text NULL,
    must_implement text NULL,
    item_order text NULL
);

CREATE TABLE IF NOT EXISTS sdc.template_instance (
    template_instance_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_instance_version_guid text NULL,
    template_instance_version_uri text NULL,
    template_sdc_id integer NOT NULL REFERENCES sdc.template_sdc(template_sdc_id),
    instance_version_date text NULL,
    diag_report_props text NULL,
    surg_path_sdcid text NULL,
    person_id integer NULL,
    visit_occurrence_id integer NULL,
    provider_id integer NULL,
    report_text text NULL
);

CREATE TABLE IF NOT EXISTS sdc.sdc_report (
    sdc_report_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_instance_id integer NULL REFERENCES sdc.template_instance(template_instance_id),
    template_name text NOT NULL,
    template_version text NOT NULL,
    template_instance_guid text NOT NULL,
    person_id integer NULL,
    visit_occurrence_id integer NULL,
    provider_id integer NULL,
    report_text text NULL,
    report_template_source text NULL,
    report_template_id text NULL,
    report_template_version_id text NULL,
    tumor_site text NULL,
    procedure_type text NULL,
    specimen_laterality text NULL,
    report_accession text NULL,
    report_loinc text NULL,
    is_duplicate_accession boolean NOT NULL DEFAULT false,
    first_seen_report_id integer NULL REFERENCES sdc.sdc_report(sdc_report_id),
    created_datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sdc.sdc_form_answer (
    sdc_form_answer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_instance_id integer NULL REFERENCES sdc.template_instance(template_instance_id),
    parent_form_answer_id integer NULL REFERENCES sdc.sdc_form_answer(sdc_form_answer_id),
    section_sdcid text NULL,
    section_guid text NULL,
    question_text text NULL,
    question_instance_guid text NULL,
    question_sdcid text NULL,
    list_item_id text NULL,
    list_item_text text NULL,
    list_item_instance_guid text NULL,
    list_item_parent_guid text NULL,
    units_system text NULL,
    response text NULL,
    units varchar NULL,
    response_int integer NULL,
    response_float numeric NULL,
    response_datetime date NULL,
    reponse_string_nvarchar varchar NULL,
    datatype text NULL,
    sdc_order text NULL,
    sdc_repeat_level text NULL,
    sdc_comments text NULL
);
