CREATE SCHEMA IF NOT EXISTS naaccr;

CREATE TABLE IF NOT EXISTS naaccr.naaccr_item (
    item_num integer PRIMARY KEY,
    name text NULL,
    xml_id text NULL
);

CREATE TABLE IF NOT EXISTS naaccr.staging_schema (
    schema_id_number text PRIMARY KEY,
    schema_id text NULL,
    schema_name text NULL
);

CREATE TABLE IF NOT EXISTS naaccr.schema_selection_rule (
    schema_selection_rule_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_id_number text NOT NULL REFERENCES naaccr.staging_schema(schema_id_number),
    site text NULL,
    histology text NULL,
    behavior text NULL,
    sex_at_birth text NULL,
    discriminator_1 text NULL,
    discriminator_2 text NULL,
    year_dx text NULL
);

CREATE TABLE IF NOT EXISTS naaccr.schema_item (
    schema_id_number text NOT NULL REFERENCES naaccr.staging_schema(schema_id_number),
    item_num integer NOT NULL REFERENCES naaccr.naaccr_item(item_num),
    used_for_staging text NULL,
    default_value text NULL,
    description text NULL,
    rationale text NULL,
    additional_info text NULL,
    table_notes text NULL,
    coding_guidelines text NULL,
    PRIMARY KEY (schema_id_number, item_num)
);

CREATE TABLE IF NOT EXISTS naaccr.registry (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS naaccr.schema_item_requirement (
    schema_item_requirement_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_id_number text NOT NULL,
    item_num integer NOT NULL,
    registry_id integer NOT NULL REFERENCES naaccr.registry(id),
    is_required boolean NOT NULL,
    FOREIGN KEY (schema_id_number, item_num) REFERENCES naaccr.schema_item(schema_id_number, item_num)
);

CREATE TABLE IF NOT EXISTS naaccr.schema_item_code (
    schema_id_number text NOT NULL,
    item_num integer NOT NULL,
    code text NOT NULL,
    description text NULL,
    PRIMARY KEY (schema_id_number, item_num, code),
    FOREIGN KEY (schema_id_number, item_num) REFERENCES naaccr.schema_item(schema_id_number, item_num)
);

CREATE TABLE IF NOT EXISTS naaccr.naaccr_concept_map (
    item_num integer PRIMARY KEY REFERENCES naaccr.naaccr_item(item_num),
    concept_id integer NOT NULL,
    concept_code text NULL,
    concept_name text NULL,
    domain_id text NULL
);

CREATE TABLE IF NOT EXISTS naaccr.naaccr_value_concept_map (
    item_num integer NOT NULL,
    code text NOT NULL,
    concept_id integer NOT NULL,
    concept_code text NULL,
    concept_name text NULL,
    PRIMARY KEY (item_num, code)
);

CREATE TABLE IF NOT EXISTS naaccr.naaccr_value (
    naaccr_value_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id integer NOT NULL,
    episode_key text NOT NULL,
    -- logical reference to sdc.sdc_report.sdc_report_id; not an enforced FK (cross-schema/attached-DB)
    sdc_report_id integer NULL,
    report_accession text NULL,
    schema_id_number text NULL,
    item_num integer NOT NULL,
    value_code text NULL,
    value_num double precision NULL,
    value_unit_source text NULL,
    observation_date date NULL
);

CREATE INDEX IF NOT EXISTS idx_naaccr_value_sdc_report
    ON naaccr.naaccr_value (sdc_report_id);
