CREATE SCHEMA IF NOT EXISTS naaccr;

-- Gap #1: algorithm + version as a first-class dimension. Every dictionary row is
-- scoped to a (algorithm, version) generation so multiple NAACCR/staging versions
-- can coexist and captured answers can record the version they were coded against.
CREATE TABLE IF NOT EXISTS naaccr.data_dictionary_version (
    dd_version_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    algorithm text NOT NULL,
    version text NOT NULL,
    naaccr_version text NULL,
    valid_start_date date NULL,
    valid_end_date date NULL,
    is_current boolean NOT NULL DEFAULT true,
    source_api text NULL,
    loaded_at timestamp NOT NULL DEFAULT now(),
    UNIQUE (algorithm, version)
);

CREATE TABLE IF NOT EXISTS naaccr.staging_schema (
    dd_version_id integer NOT NULL REFERENCES naaccr.data_dictionary_version(dd_version_id),
    schema_id_number text NOT NULL,
    schema_id text NULL,
    schema_name text NULL,
    PRIMARY KEY (dd_version_id, schema_id_number)
);

CREATE TABLE IF NOT EXISTS naaccr.schema_selection_rule (
    schema_selection_rule_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dd_version_id integer NOT NULL,
    schema_id_number text NOT NULL,
    site text NULL,
    histology text NULL,
    behavior text NULL,
    sex_at_birth text NULL,
    discriminator_1 text NULL,
    discriminator_2 text NULL,
    year_dx text NULL,
    FOREIGN KEY (dd_version_id, schema_id_number)
        REFERENCES naaccr.staging_schema(dd_version_id, schema_id_number)
);

CREATE TABLE IF NOT EXISTS naaccr.naaccr_item (
    dd_version_id integer NOT NULL REFERENCES naaccr.data_dictionary_version(dd_version_id),
    item_num integer NOT NULL,
    name text NULL,
    xml_id text NULL,
    -- Gap #2a: field metadata available from the SEER Staging API (per-input unit/decimals).
    unit text NULL,
    decimal_places integer NULL,
    -- Gap #2b: field metadata from the NAACCR Data Dictionary API / imsweb layout.
    -- Nullable so the staging-only load works before the DD-API enrichment runs.
    data_type text NULL,
    length integer NULL,
    padding text NULL,
    alignment text NULL,
    trim text NULL,
    section text NULL,
    parent_xml_element text NULL,
    PRIMARY KEY (dd_version_id, item_num)
);

CREATE TABLE IF NOT EXISTS naaccr.schema_item (
    dd_version_id integer NOT NULL,
    schema_id_number text NOT NULL,
    item_num integer NOT NULL,
    -- Gap #4: distinguish captured inputs from derived staging outputs.
    item_role text NOT NULL DEFAULT 'input',
    used_for_staging text NULL,
    default_value text NULL,
    description text NULL,
    rationale text NULL,
    additional_info text NULL,
    table_notes text NULL,
    coding_guidelines text NULL,
    PRIMARY KEY (dd_version_id, schema_id_number, item_num),
    FOREIGN KEY (dd_version_id, schema_id_number)
        REFERENCES naaccr.staging_schema(dd_version_id, schema_id_number),
    FOREIGN KEY (dd_version_id, item_num)
        REFERENCES naaccr.naaccr_item(dd_version_id, item_num)
);

CREATE TABLE IF NOT EXISTS naaccr.registry (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS naaccr.schema_item_requirement (
    schema_item_requirement_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dd_version_id integer NOT NULL,
    schema_id_number text NOT NULL,
    item_num integer NOT NULL,
    registry_id integer NOT NULL REFERENCES naaccr.registry(id),
    is_required boolean NOT NULL,
    UNIQUE (dd_version_id, schema_id_number, item_num, registry_id),
    FOREIGN KEY (dd_version_id, schema_id_number, item_num)
        REFERENCES naaccr.schema_item(dd_version_id, schema_id_number, item_num)
);

CREATE TABLE IF NOT EXISTS naaccr.schema_item_code (
    dd_version_id integer NOT NULL,
    schema_id_number text NOT NULL,
    item_num integer NOT NULL,
    code text NOT NULL,
    description text NULL,
    PRIMARY KEY (dd_version_id, schema_id_number, item_num, code),
    FOREIGN KEY (dd_version_id, schema_id_number, item_num)
        REFERENCES naaccr.schema_item(dd_version_id, schema_id_number, item_num)
);

-- Gap #3: persist the SEER staging lookup tables (the value-validation / staging
-- building blocks). Natural-keyed on (dd_version_id, table_key). Row cells are stored
-- as a JSON array of strings so the shape is portable across all three dialects.
CREATE TABLE IF NOT EXISTS naaccr.staging_table (
    dd_version_id integer NOT NULL REFERENCES naaccr.data_dictionary_version(dd_version_id),
    table_key text NOT NULL,
    name text NULL,
    title text NULL,
    subtitle text NULL,
    description text NULL,
    notes text NULL,
    coding_guidelines text NULL,
    PRIMARY KEY (dd_version_id, table_key)
);

CREATE TABLE IF NOT EXISTS naaccr.staging_table_column (
    dd_version_id integer NOT NULL,
    table_key text NOT NULL,
    col_index integer NOT NULL,
    col_key text NULL,
    col_name text NULL,
    col_type text NULL,
    col_source text NULL,
    PRIMARY KEY (dd_version_id, table_key, col_index),
    FOREIGN KEY (dd_version_id, table_key)
        REFERENCES naaccr.staging_table(dd_version_id, table_key)
);

CREATE TABLE IF NOT EXISTS naaccr.staging_table_row (
    dd_version_id integer NOT NULL,
    table_key text NOT NULL,
    row_index integer NOT NULL,
    cells text NULL, -- JSON array of cell values, ordered by col_index
    PRIMARY KEY (dd_version_id, table_key, row_index),
    FOREIGN KEY (dd_version_id, table_key)
        REFERENCES naaccr.staging_table(dd_version_id, table_key)
);

CREATE TABLE IF NOT EXISTS naaccr.schema_involved_table (
    dd_version_id integer NOT NULL,
    schema_id_number text NOT NULL,
    table_key text NOT NULL,
    PRIMARY KEY (dd_version_id, schema_id_number, table_key),
    FOREIGN KEY (dd_version_id, schema_id_number)
        REFERENCES naaccr.staging_schema(dd_version_id, schema_id_number),
    FOREIGN KEY (dd_version_id, table_key)
        REFERENCES naaccr.staging_table(dd_version_id, table_key)
);

-- OMOP concept maps are version-independent: a NAACCR item / value code maps to the
-- same OMOP concept regardless of dictionary version, and the ETL bridge joins on
-- item_num / (item_num, code) alone. So they are keyed on item_num only and reference
-- naaccr_item logically (no composite FK).
CREATE TABLE IF NOT EXISTS naaccr.naaccr_concept_map (
    item_num integer PRIMARY KEY,
    concept_id integer NOT NULL,
    concept_code text NULL,
    concept_name text NULL,
    domain_id text NULL
);

CREATE TABLE IF NOT EXISTS naaccr.naaccr_value_concept_map (
    item_num integer NOT NULL,
    code text NOT NULL,
    concept_id integer NOT NULL,
    concept_code text NULL,
    concept_name text NULL,
    PRIMARY KEY (item_num, code)
);

CREATE TABLE IF NOT EXISTS naaccr.naaccr_value (
    naaccr_value_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id integer NOT NULL,
    episode_key text NOT NULL,
    -- logical reference to sdc.sdc_report.sdc_report_id; not an enforced FK (cross-schema/attached-DB)
    sdc_report_id integer NULL,
    report_accession text NULL,
    schema_id_number text NULL,
    item_num integer NOT NULL,
    obx_sub_id text NULL,
    value_code text NULL,
    value_num double precision NULL,
    value_text text NULL,
    value_unit_source text NULL,
    observation_date date NULL,
    -- Gap #1: the dictionary version this answer was coded against. Nullable so existing
    -- import paths that do not yet supply it keep working; populate going forward.
    dd_version_id integer NULL REFERENCES naaccr.data_dictionary_version(dd_version_id)
);

CREATE INDEX IF NOT EXISTS idx_naaccr_value_sdc_report
    ON naaccr.naaccr_value (sdc_report_id);
CREATE INDEX IF NOT EXISTS idx_naaccr_value_person_episode
    ON naaccr.naaccr_value (person_id, episode_key);
CREATE INDEX IF NOT EXISTS idx_naaccr_value_report_item
    ON naaccr.naaccr_value (report_accession, item_num);
CREATE INDEX IF NOT EXISTS idx_naaccr_value_item_code
    ON naaccr.naaccr_value (item_num, value_code);
