<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\database\schemas\**\ddl\sqlite\*.sql" Link="database\schemas\%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\..\database\etl\sqlite\*.sql" Link="database\etl\sqlite\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SdcCdm\SdcCdm.csproj" />
  </ItemGroup>

</Project>
